os: windows
language: shell

stages:
  - test
  - name: deploy
    if: type = push AND fork = false AND env(nuget_key) IS present

before_script:
  - choco install visualstudio2019-workload-netcorebuildtools
  - powershell Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
  - dotnet restore
  - dotnet build -c Release

jobs:
  include: 
  - stage: test
    name: "Unit Tests"
    script: dotnet test
    
  - name: "Demo Run"
    script: dotnet run --project ".\DragonFruit.Six.API.Demo"
    
  - name: "Code Quality"
    script:
      - choco install resharper-clt.portable
      - InspectCode.exe DragonFruit.Six.API.sln -o=results.xml
      
  - stage: deploy
    name: "Beta"
    script: powershell -File Nuget.ps1 -Suffix "-beta"
    if: branch = master
    
  - name: "Production"
    script: powershell -File Nuget.ps1
    if: branch = production
